### ISSUE TITLE
index out of range error when running `uds` without arguments

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/uds-cli#328]
### Environment

Device and OS: Apple M2 Max, macOS Sonoma v14.2.1
App version: 0.6.1
Kubernetes distro being used: N/A
Other: N/A

### Steps to reproduce

1. install uds-cli using asdf plugin
2. run `uds version`
3. run `uds`

### Expected result

I see usage/help output

### Actual Result

```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/defenseunicorns/uds-cli/src/cmd.init.1()
        /home/runner/work/uds-cli/uds-cli/src/cmd/root.go:76 +0x578
```

### Additional Context

```
andrewgreene in ~/repos/gh/snc-atoms-uds-bundle on main λ asdf local uds-cli 0.6.1
andrewgreene in ~/repos/gh/snc-atoms-uds-bundle on main λ uds version
v0.6.1
andrewgreene in ~/repos/gh/snc-atoms-uds-bundle on main λ uds
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/defenseunicorns/uds-cli/src/cmd.init.1()
        /home/runner/work/uds-cli/uds-cli/src/cmd/root.go:76 +0x578
```

**Comment by andrewg-xyz** [comment]
Confirmed with local build
commit: `7624fe1 (HEAD -> main, origin/main, origin/HEAD) chore(deps): update github/codeql-action action to v3.23.1 (#326)`
built using `make build-cli-mac-apple` and go v 1.21.5

```
andrewgreene in ~/repos/gh/uds-cli on main ● λ ./build/uds-mac-apple 
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/defenseunicorns/uds-cli/src/cmd.init.1()
        /Users/andrewgreene/repos/gh/uds-cli/src/cmd/root.go:76 +0x578
```

**Comment by UncleGedd** [comment]
Good catch, thanks for reporting, will prioritize and fix ASAP
