### ISSUE TITLE
UDS-Cli - index out of range error

### ISSUE THREAD

**Issue by benmountjoy111** [defenseunicorns/uds-cli#617]
### Environment

Device and OS: Ubuntu 22.04.4
App version: v0.10.4
Kubernetes distro being used:  v1.28.9+rke2r1
Other:

### Steps to reproduce

1. create uds-bundle (see uds-bundle.yaml below)
2. Deploy the newly created uds-bundle: `uds deploy uds-bundle-dco-core-amd64-0.2.1.tar.zst --confirm`

### Expected result
Bundle deploys

### Actual Result
cli outputs error

### Visual Proof (screenshots, videos, text, etc)
```
uds deploy uds-bundle-dco-core-amd64-0.2.1.tar.zst --confirm

 NOTE  Using config file /home/voltron/ben/dco-core/bundles/uds-config.yaml
  DEBUG   2024-05-16T15:15:04Z  -  Log level set to debug

   ╭──────────────────────╮   
   │                      │   
   │ UDS Bundle: dco-core │   
   │                      │   
   ╰──────────────────────╯   

    📦 Deploying bundle package (2 / 7)    
                       
    <l> Toggle logs    
                                                             
    ✔ Package uds-setup-package deployed                     
                                                             
    ⣻  Package init-longhorn deploying (1 / 7 components)    
                                                             
Caught panic:

runtime error: index out of range [7] with length 7

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:478 +0x91
panic({0x4616220?, 0xc003452fa8?})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:920 +0x270
github.com/defenseunicorns/uds-cli/src/pkg/bundle/tui/deploy.(*Model).handleDeployTick(0xc0009ff400)
	/home/runner/work/uds-cli/uds-cli/src/pkg/bundle/tui/deploy/handlers.go:179 +0x325
github.com/defenseunicorns/uds-cli/src/pkg/bundle/tui/deploy.(*Model).Update(0xc0009ff400, {0x443b3c0?, 0xc0021185b8?})
	/home/runner/work/uds-cli/uds-cli/src/pkg/bundle/tui/deploy/model.go:188 +0x9aa
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc001f76000, {0x59366c8?, 0xc0009ff400?}, 0xc001d3f508?)
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:411 +0x75a
github.com/charmbracelet/bubbletea.(*Program).Run(0xc001f76000)
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:543 +0x86e
github.com/defenseunicorns/uds-cli/src/cmd.glob..func9(0x832dfe0?, {0xc0009ebfa0?, 0x4?, 0x49144fd?})
	/home/runner/work/uds-cli/uds-cli/src/cmd/uds.go:91 +0x346
github.com/spf13/cobra.(*Command).execute(0x832dfe0, {0xc0009ebf60, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x832e2c0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/defenseunicorns/uds-cli/src/cmd.Execute()
	/home/runner/work/uds-cli/uds-cli/src/cmd/root.go:59 +0x1a
main.main()
	/home/runner/work/uds-cli/uds-cli/main.go:21 +0x5f
```

### Severity/Priority
Low (can workaround it with `--no-tea` flag)

### Additional Context

Add any other context or screenshots about the technical debt here.
`uds-bundle.yaml`

```
kind: UDSBundle
metadata:
  name: dco-core
  description: The meat and potatoes of dco. The bedrock. The nuts and bolts. The first lego block.
  architecture: amd64
  version: 0.2.1 

packages:
  - name: uds-setup-package
    path: ../build/
    ref: v0.0.1

  - name: init-longhorn
    repository: oci://ghcr.io/naps-dev/packages/init-longhorn
    ref: v0.32.4

  - name: metallb-package
    path: ../build/
    ref: v0.14.4
    overrides:
      metallb-config:
        metallb-config-chart:
          variables:
            # Override metallb interface and IP address pool at deploy-time
            - name: METALLB_IP_ADDRESS_POOL
              path: ipAddressPool
              description: "Range of IPs metallb should use for external IPs"
            - name: METALLB_INTERFACE
              path: interface
              description: "Interface used for L2 advertisements"

  - name: uds-core
    repository: oci://ghcr.io/defenseunicorns/packages/uds/core
    ref: 0.21.1-registry1
    overrides:
      loki:
        loki:
          values:
            - path: "global.dnsService"
              value: "rke2-coredns-rke2-coredns"
      istio-controlplane:
        istiod:
          values:
            - path: "global.proxy.resources.requests.memory"
              value: "56Mi"
      istio-admin-gateway:
        gateway:
          values:
            - path: "service.ports"
              value:
                - port: 15021
                  targetPort: 15021
                  name: status-port
                  protocol: TCP
                - port: 80
                  targetPort: 8080
                  name: http2
                  protocol: TCP
                - port: 443
                  targetPort: 8443
                  name: https
                  protocol: TCP
                - port: 1514
                  targetPort: 1514
                  name: wazuh-agent
                  protocol: TCP
                - port: 1515
                  targetPort: 1515
                  name: wazuh-registration
                - port: 55000
                  targetPort: 55000
                  name: wazuh-api
  - name: pepr-exemptions-package
    path: ../build/
    ref: v0.0.1

  - name: uds-config-addons-package
    path: ../build/
    ref: v1.21.2

  - name: dco-core-no-dubbd-package
    path: ../build/
    ref: v0.0.1

**Comment by UncleGedd** [comment]
Closing bc we nixed the TUI: https://github.com/defenseunicorns/uds-cli/blob/main/adr/0004-tui.md
